INSERT INTO signo (tipo, nombre, marca) VALUES
('grafica', NULL, 1),
('mixta', 'H HANNA', 2),
('mixta', 'SINOCHEM', 3),
('denominativa', 'BROWNIE', 4),
('mixta', 'INDUSTRIAS JHOSDAM', 5),
('denominativa', 'JNTL CONSUMER HEALTH', 6),
('grafica', NULL, 7),
('denominativa', 'OH MY DOG', 8),
('mixta', 'LAS IDEALES', 9),
('mixta', 'RDA', 10),
('mixta', 'AIR WILLSON W1', 11),
('denominativa', 'GLAFF PHARMACEUTICALS', 12),
('mixta', 'CLINICAS CLEO', 13),
('denominativa', 'TIKTOK MUSIC', 14),
('mixta', 'A TE ENAMORA', 15),
('mixta', 'TATO', 16),
('mixta', 'MURASAKI', 17),
('mixta', 'FRANCHETTI', 18),
('denominativa', 'OLANZATIQUE', 19),
('mixta', 'BUZA CREAM', 20),
('mixta', 'TOP IGNITION', 21),
('denominativa', 'BIONTECH', 22),
('denominativa', 'BIONTECH', 23),
('grafica', NULL, 24),
('mixta', 'SOLINTEX', 25),
('denominativa', 'VENGRANO', 26),
('mixta', 'CAFE MORAN', 27),
('mixta', 'MORELLA', 28),
('denominativa', 'DICLODEX', 29),
('denominativa', 'LA FANATICA VINOTINTO', 30),
('mixta', 'GANDOUR', 31),
('mixta', 'TAWALA LEGION', 32),
('mixta', 'PAPELONYA', 33),
('mixta', 'T', 34),
('denominativa', 'APECOIN', 35),
('denominativa', 'LA DEAR', 36),
('denominativa', 'UBAI', 37),
('mixta', 'POLAR SINCE 1941', 38),
('denominativa', 'GRENDENE', 39),
('denominativa', 'RIOT GAMES', 40),
('mixta', 'NUTRI DELHI', 41),
('mixta', 'LA SALLE', 42),
('denominativa', 'ALKEGEN', 43),
('mixta', 'ARKEMA', 44),
('denominativa', 'META PORTAL', 45),
('mixta', 'ALIMENTOS TRINIDAD', 46),
('denominativa', 'VENEUSA', 47),
('mixta', 'ALIMENTOS VILLATERRA', 48),
('mixta', 'LA CAVA EST.1995', 49),
('denominativa', 'IDHEA STORE', 50),
('denominativa', 'FEMIVITAL', 51),
('denominativa', 'LA BONA', 52),
('mixta', 'ZONA ROSAL', 53),
('mixta', 'R', 54),
('mixta', 'R', 55),
('mixta', 'RIDERY', 56),
('mixta', 'BAO BAO', 57),
('mixta', 'TSINGYUAN', 58),
('mixta', 'PITAPOLLO', 59),
('mixta', 'ICC', 60),
('denominativa', 'WALGREENS', 61),
('denominativa', 'CARBAXIN', 62),
('mixta', 'OSTWINT PROFESSIONAL', 63),
('denominativa', 'RESVELDEN', 64),
('mixta', 'GOSSIP', 65),
('mixta', 'METAFRAX GROUP', 66),
('denominativa', 'ARIZI', 67),
('denominativa', 'DULCOXUNI', 68),
('mixta', 'FOODKART', 69),
('denominativa', 'REELS', 70),
('denominativa', 'REGINA BY EC', 71),
('mixta', 'GALLETAS PUIG CRASKI BRAN', 72),
('mixta', 'CONFITERIA LA GUACAMAYA', 73),
('mixta', 'PLANETA DULCE', 74),
('grafica', NULL, 75),
('denominativa', '¡LOS DE LA CAJITA AZUL!', 76),
('mixta', 'POMPOSSO', 77),
('mixta', 'PITAHAYA MEDIA MARKETING', 78),
('denominativa', 'DON LUCIANO', 79),
('mixta', 'MEDFALCH', 80),
('denominativa', 'INSPIRE GREATNESS', 81),
('mixta', 'BIOZTRONICS', 82),
('denominativa', 'METAONE', 83),
('denominativa', 'SIKASCREED', 84),
('denominativa', 'CESAR SHOES', 85),
('mixta', 'LOS ROSALES', 86),
('mixta', 'PINK SILVER', 87),
('mixta', 'TELLUS POWER', 88),
('mixta', 'EL CLUB DE LAS PAYASITAS', 89),
('mixta', 'CLAVO VARETA C.A. MEJIA & CIA', 90),
('mixta', 'TRITON', 91),
('denominativa', 'CAPITAL GRILL', 92),
('mixta', 'POSITEX', 93),
('mixta', 'WAFER 365 XL', 94),
('mixta', 'OG', 95),
('denominativa', 'SACA EL PECHO FEST', 96),
('mixta', 'PLASTICOS CELIA', 97),
('mixta', 'AION', 98),
('mixta', 'MEETION', 99),
('mixta', 'NUTRIT YEAST', 100),
('mixta', 'O2 OXIVEN', 101),
('denominativa', 'VERSITIV', 102),
('mixta', 'LATITUD SEGUROS', 103),
('denominativa', 'NIREDON', 104),
('mixta', 'MATILDA', 105),
('grafica', NULL, 106),
('mixta', 'LV', 107),
('grafica', NULL, 108),
('grafica', NULL, 109),
('mixta', 'PEROS', 110),
('mixta', 'LOS LLANOS', 111),
('denominativa', 'LEO', 112),
('mixta', 'LA TOSCANA', 113),
('mixta', 'CAFE CENDE', 114),
('grafica', NULL, 115),
('denominativa', 'MIARROZ', 116),
('mixta', 'REDDOT', 117),
('mixta', 'GRUPO MC', 118),
('mixta', 'GRUPO MC', 119),
('mixta', 'HD', 120),
('denominativa', 'KEJUMALU', 121),
('mixta', 'MULTIMALL CENTER', 122),
('mixta', 'SARITA', 123),
('mixta', 'AIKOZ', 124),
('mixta', 'GREEN TIDE EXTRACTO DE ALGA', 125),
('denominativa', 'PRONOV', 126),
('mixta', 'EMELIE', 127),
('mixta', 'LA SANAHORIA', 128),
('denominativa', 'SBR', 129),
('denominativa', 'EL FRUTO DE UNA TRADICION', 130),
('mixta', 'MANGUANGUA', 131),
('mixta', 'ARQOS', 132),
('grafica', NULL, 133),
('mixta', 'Gansito', 134),
('denominativa', 'BIOFARM', 135),
('mixta', 'CHUCHO CAFE', 136),
('grafica', NULL, 137),
('mixta', 'MAVESA', 138),
('mixta', 'ASTRO100', 139),
('denominativa', 'FARMACIA RIO', 140),
('mixta', 'AGRO SIMON SEMBRAMOS AGRONEGOCIOS', 141),
('denominativa', 'MAS QUE HAMBURGUESAS', 142),
('denominativa', 'MAROLIO', 143),
('grafica', NULL, 144),
('denominativa', 'VCRenewables', 145),
('denominativa', 'SIENTE LA COCINA', 146),
('denominativa', 'SIENTE LA COCINA', 147),
('mixta', 'CAFE PALMA REAL', 148),
('denominativa', 'VIRTUOSO', 149),
('denominativa', 'DURAMAX', 150),
('denominativa', 'KRONUTS', 151),
('mixta', 'MERLIN', 152),
('denominativa', 'ECO RHELEN', 153),
('mixta', 'CHAIN A LA PARRILLA', 154),
('denominativa', 'SALMTECH', 155),
('denominativa', 'VENTO', 156),
('mixta', 'PEPSI', 157),
('grafica', NULL, 158),
('mixta', 'DECOPAINT', 159),
('mixta', 'PAFIA', 160),
('denominativa', 'PERPETUAL 1908', 161),
('denominativa', 'ISOTRETIN', 162),
('denominativa', 'ALTA D', 163),
('denominativa', 'FIRMFIT', 164),
('mixta', 'MANPA ECOLOGY SUTIL', 165),
('mixta', 'MINISO', 166),
('mixta', 'PAOLA STUDIO', 167),
('denominativa', 'NULLO WEB', 168),
('mixta', 'THOM SAILOR', 169),
('mixta', 'M', 170),
('mixta', 'QUEENS LEAGUE', 171),
('mixta', 'SUNTY MANZANA', 172),
('denominativa', 'CAFE SEMPITERNO', 173),
('mixta', 'ORIENTAL', 174),
('mixta', 'TU ALIADO', 175),
('mixta', 'MOTUL EGEN', 176),
('mixta', 'PALUZ', 177),
('denominativa', 'YALA', 178),
('mixta', 'ABBA ENMANUEL', 179),
('mixta', 'BISTON', 180),
('mixta', 'SMART HOME', 181),
('mixta', 'JOHNSON&JOHNSON', 182),
('denominativa', 'SOL DE JANEIRO', 183),
('mixta', 'OMEGA ELECTRONICS', 184),
('denominativa', 'CHOCOLATE LATINOAMERICANO SOSTENIBLE', 185),
('denominativa', 'BARBEBIEN', 186),
('mixta', 'ZAMUSA', 187),
('denominativa', 'ZUBI', 188),
('denominativa', 'SAINT LAURENT', 189),
('mixta', 'XETUX', 190),
('mixta', 'PINTURAS COINPICA', 191),
('mixta', 'LEVARE', 192),
('denominativa', 'GREINO', 193),
('mixta', 'DELANTO', 194),
('denominativa', 'SABRE', 195),
('mixta', 'YOY', 196),
('denominativa', 'NIZOX', 197),
('mixta', 'CALIFORNIA COLLECTION', 198),
('mixta', 'IMPOL', 199),
('grafica', NULL, 200),
('mixta', 'AIKOZ', 201),
('denominativa', 'THYGENEXT', 202),
('denominativa', 'RASPA TU SUERTE', 203),
('denominativa', 'FEMDIEN', 204),
('mixta', 'BIMBA Y LOLA', 205),
('mixta', 'Gmillet', 206),
('denominativa', 'PROBIOMED', 207),
('denominativa', 'MEGAN BATLA', 208),
('mixta', 'ROSWILL', 209),
('mixta', 'LUATEK', 210),
('mixta', 'MAREAH', 211),
('mixta', 'ARABITO FERRETERIAS', 212),
('denominativa', 'EVOLUTION', 213),
('mixta', 'MAXWELL', 214),
('mixta', 'SEU ALIMENTOS', 215),
('mixta', 'FLUXUS', 216),
('mixta', 'T TAWALA', 217),
('mixta', 'WILD OLIVE', 218),
('mixta', 'KALY', 219),
('denominativa', 'HANA', 220),
('mixta', 'MOLINA VIAJES', 221),
('mixta', 'PREMIER PADEL', 222),
('mixta', 'LABANCALAW', 223),
('grafica', NULL, 224),
('mixta', 'B BESTANDIG APPLIANCES', 225),
('mixta', 'B BESTANDIG APPLIANCES', 226),
('mixta', 'GATHOPE', 227),
('denominativa', 'NOPUCID', 228),
('denominativa', 'MAPLE ACE', 229),
('denominativa', 'AVENIDA HOME', 230),
('denominativa', 'INNOVACION A TU ALCANCE', 231),
('mixta', 'SOR', 232),
('mixta', 'SOR', 233),
('denominativa', 'PAISAJE GLOBAL', 234),
('denominativa', 'CITRACELL-PROTECT', 235),
('mixta', 'M M', 236),
('mixta', 'FarmaPay', 237),
('mixta', 'AGC YOUR DREAMS, OUR CHALLENGE', 238),
('mixta', 'ASTER', 239),
('mixta', 'IZY', 240),
('mixta', 'LUVENE', 241),
('denominativa', 'CELAFLOR', 242),
('mixta', 'MENTALINK', 243),
('mixta', 'ZETA´S MOTORCYCLE PARTS', 244),
('mixta', 'MI REGALO PA CHAVEZ ES VOTANDO', 245),
('mixta', 'HO.LA', 246),
('mixta', 'PORTADAS AL DIA', 247),
('mixta', 'FEITIAN', 248),
('denominativa', 'APPLE SPORTS', 249),
('denominativa', 'KERAKOLL', 250),
('mixta', 'PERFECT SENSE', 251),
('denominativa', 'GIOVANNI SCUTARO MILANO', 252),
('denominativa', 'PEPECOOL', 253),
('grafica', NULL, 254),
('denominativa', 'ANTADYS', 255),
('mixta', 'ROC', 256),
('mixta', 'MOLLY', 257),
('mixta', 'NEXGO CLOUD', 258),
('denominativa', 'GLICEMIN', 259),
('mixta', 'VDI', 260),
('mixta', 'JUEGOS INDIGENAS', 261),
('mixta', 'FVF', 262),
('mixta', 'XTREME PERFORMANCE', 263),
('mixta', 'HIPOCAMPO SALA SHOW', 264),
('mixta', 'HUMMER', 265),
('denominativa', 'ACTYON', 266),
('mixta', 'WOLF BY EBITEN', 267),
('denominativa', 'FERREXEL', 268),
('mixta', 'ÜMA', 269),
('mixta', 'UDUKE', 270),
('denominativa', 'MAUREL & PROM', 271),
('denominativa', 'RUTILARC', 272),
('mixta', 'EBC COLLECTION', 273),
('mixta', 'SHOFU', 274),
('denominativa', 'ALLY', 275),
('denominativa', 'ZIU', 276),
('mixta', 'INTACO', 277),
('mixta', 'KUENTRO', 278),
('mixta', 'R', 279),
('denominativa', 'PENOTTI', 280),
('grafica', NULL, 281),
('mixta', 'MUSAI', 282),
('mixta', 'CAMEL', 283),
('denominativa', 'CINES UNIDOS CLUB', 284),
('denominativa', 'CONECTADOS CON TU VIDA', 285),
('denominativa', 'ATTIMO', 286),
('mixta', 'TEDEXIS', 287),
('mixta', 'MAXPRO', 288),
('denominativa', 'SOFTMOVE', 289),
('mixta', '+QCAMPUS', 290),
('denominativa', 'SYNTHESIA TECHNOLOGY', 291),
('denominativa', 'ECARVIT', 292),
('mixta', 'DON VILLA', 293),
('denominativa', 'KHOUDARY', 294),
('denominativa', 'LA EXPERIENCIA DE GANAR', 295),
('denominativa', 'PLAYA SECA POLAR LIGHT', 296),
('mixta', 'FLIGHT', 297),
('mixta', 'GRAN LOGIA DE LA REPUBLICA DE VENEZUELA', 298),
('mixta', 'ACCUMES', 299),
('mixta', 'SIMPLE', 300);