DROP TABLE solicitud CASCADE;

DROP TABLE marca CASCADE;

DROP TABLE prioridad_extranjera CASCADE;

DROP TABLE prioriza CASCADE;

DROP TABLE signo CASCADE;

DROP TABLE pais CASCADE;

DROP TABLE solicitante CASCADE;

DROP TABLE solicita CASCADE;

DROP TABLE solicitante_natural CASCADE;